// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUjdNt4cW3ZcKpbtksnBvEFpNrpmJ4G2U',
    appId: '1:987184857149:web:d8f1401e308aaaa363aa54',
    messagingSenderId: '987184857149',
    projectId: 'news-read-project',
    authDomain: 'news-read-project.firebaseapp.com',
    storageBucket: 'news-read-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsOdLaMTuK1RBTcxKVcoMqRldj2eyFrMU',
    appId: '1:987184857149:android:5b0a9e9189b858af63aa54',
    messagingSenderId: '987184857149',
    projectId: 'news-read-project',
    storageBucket: 'news-read-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByfKxmjbrVj4Ba03ssPw8X1mgIBePdS5o',
    appId: '1:987184857149:ios:d294cbb249ecee0c63aa54',
    messagingSenderId: '987184857149',
    projectId: 'news-read-project',
    storageBucket: 'news-read-project.appspot.com',
    androidClientId: '987184857149-cdq9j36c98ddrc6hq1hk1i1a6jl0p3mm.apps.googleusercontent.com',
    iosClientId: '987184857149-gcmjvm8h95uibrth2gtg5n5t3hosnmsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByfKxmjbrVj4Ba03ssPw8X1mgIBePdS5o',
    appId: '1:987184857149:ios:d294cbb249ecee0c63aa54',
    messagingSenderId: '987184857149',
    projectId: 'news-read-project',
    storageBucket: 'news-read-project.appspot.com',
    androidClientId: '987184857149-cdq9j36c98ddrc6hq1hk1i1a6jl0p3mm.apps.googleusercontent.com',
    iosClientId: '987184857149-gcmjvm8h95uibrth2gtg5n5t3hosnmsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodPro',
  );
}
